### PR TITLE
Adaptive rate control enhancement

### LINKED ISSUE #1097: Not all tests are run in CI
Running test locally yields 7 failures in flint-core tests.
```
% sbt test

...

[error] Failed: Total 106, Failed 7, Errors 0, Passed 99
[error] Failed tests:
[error] 	org.opensearch.flint.core.storage.OpenSearchBulkWrapperTest
[error] 	org.opensearch.flint.core.http.RetryableHttpAsyncClientSuite
[error] 	org.opensearch.flint.core.storage.OpenSearchClientUtilsSuite
[error] (flintCore / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 688 s (11:28), completed Apr 2, 2025, 10:58:05 AM
```

Upon checking recent CI workflow, test reports show that only `integ-test`, `flint-spark-integration`, `ppl-spark-integration`, and `sql-job` tests are run.
`flint-commons` and `flint-core` are both left out.
We removed running unit tests explicitly and merge them into the integtest run: https://github.com/opensearch-project/opensearch-spark/pull/501
But now some module's UT are missing, either introduced by this change or later changes in build.sbt

We need to
1. Fix workflow or build.sbt so all UT are run
2. Fix failing UT

Below is a test report directory content uploaded by our CI
```
.
├── flint-spark-integration
│  ├── css
│  ├── images
│  ├── js
│  ├── index.html
│  ├── org.apache.spark.opensearch.catalog.OpenSearchCatalogTest.html
│  ├── org.apache.spark.sql.flint.config.FlintSparkConfSuite.html
│  ├── org.apache.spark.sql.flint.datatype.FlintDataTypeSuite.html
│  ├── org.apache.spark.sql.flint.datatype.FlintMetadataExtensionsSuite.html
│  ├── org.apache.spark.sql.flint.storage.FlintQueryCompilerSuite.html
│  ├── org.apache.spark.sql.FlintCatalogSuite.html
│  ├── org.opensearch.flint.spark.covering.ApplyFlintSparkCoveringIndexSuite.html
│  ├── org.opensearch.flint.spark.covering.FlintSparkCoveringIndexSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkCheckpointSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkIndexBuilderSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkIndexFactorySuite.html
│  ├── org.opensearch.flint.spark.FlintSparkIndexOptionsSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkIndexRefreshSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkIndexSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkTransactionSupportSuite.html
│  ├── org.opensearch.flint.spark.function.TumbleFunctionSuite.html
│  ├── org.opensearch.flint.spark.metadatacache.FlintMetadataCacheSuite.html
│  ├── org.opensearch.flint.spark.mv.FlintSparkMaterializedViewSuite.html
│  ├── org.opensearch.flint.spark.scheduler.util.RefreshQueryGeneratorTest.html
│  ├── org.opensearch.flint.spark.skipping.ApplyFlintSparkSkippingIndexSuite.html
│  ├── org.opensearch.flint.spark.skipping.bloomfilter.BloomFilterMightContainSuite.html
│  ├── org.opensearch.flint.spark.skipping.bloomfilter.BloomFilterSkippingStrategySuite.html
│  ├── org.opensearch.flint.spark.skipping.FlintSparkSkippingFileIndexSuite.html
│  ├── org.opensearch.flint.spark.skipping.FlintSparkSkippingIndexSuite.html
│  ├── org.opensearch.flint.spark.skipping.minmax.MinMaxSkippingStrategySuite.html
│  ├── org.opensearch.flint.spark.skipping.partition.PartitionSkippingStrategySuite.html
│  ├── org.opensearch.flint.spark.skipping.valueset.ValueSetSkippingStrategySuite.html
│  └── org.opensearch.flint.spark.sql.FlintSparkSqlParserSuite.html
├── integ-test
│  ├── css
│  ├── images
│  ├── js
│  ├── index.html
│  ├── org.apache.spark.FlintDataSourceV2ITSuite.html
│  ├── org.apache.spark.opensearch.catalog.OpenSearchCatalogITSuite.html
│  ├── org.apache.spark.opensearch.table.OpenSearchDashboardITSuite.html
│  ├── org.apache.spark.opensearch.table.OpenSearchTableITSuite.html
│  ├── org.apache.spark.opensearch.table.OpenSearchTableQueryITSuite.html
│  ├── org.apache.spark.sql.FlintJobITSuite.html
│  ├── org.apache.spark.sql.FlintREPLITSuite.html
│  ├── org.opensearch.flint.core.FlintMetadataLogITSuite.html
│  ├── org.opensearch.flint.core.FlintOpenSearchClientSuite.html
│  ├── org.opensearch.flint.core.FlintOpenSearchIndexMetadataServiceITSuite.html
│  ├── org.opensearch.flint.core.FlintTransactionITSuite.html
│  ├── org.opensearch.flint.core.OpenSearchUpdaterSuite.html
│  ├── org.opensearch.flint.core.scheduler.OpenSearchAsyncQuerySchedulerITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkCoveringIndexITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkCoveringIndexSqlITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkIndexDescribeITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkIndexJobITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkIndexJobSqlITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkIndexMonitorITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkIndexNameITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkIndexSqlITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkIndexValidationITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkMaterializedViewIntegrationsITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkMaterializedViewITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkMaterializedViewSqlITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkSkippingIndexITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkSkippingIndexSqlITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkTransactionITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkUpdateIndexITSuite.html
│  ├── org.opensearch.flint.spark.FlintSparkWindowingFunctionITSuite.html
│  ├── org.opensearch.flint.spark.iceberg.FlintSparkIcebergMaterializedViewITSuite.html
│  ├── org.opensearch.flint.spark.iceberg.FlintSparkIcebergSkippingIndexITSuite.html
│  ├── org.opensearch.flint.spark.metadatacache.FlintOpenSearchMetadataCacheWriterITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLAggregationsITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLAggregationWithSpanITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLAppendColITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLBasicITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLBetweenITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLBuiltInDateTimeFunctionITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLBuiltinFunctionITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLCastITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLCidrmatchITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLCommentITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLCorrelationITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLDedupeITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLEvalITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLEventstatsITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLExistsSubqueryITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLExpandITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLFieldSummaryITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLFillnullITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLFiltersITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLFlattenITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLGeoipITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLGrokITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLInSubqueryITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLJoinITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLJsonFunctionITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLLambdaFunctionITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLLookupITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLNestedFieldsITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLParseITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLPatternsITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLRenameITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLScalarSubqueryITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLTimeWindowITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLTopAndRareITSuite.html
│  ├── org.opensearch.flint.spark.ppl.FlintSparkPPLTrendlineITSuite.html
│  ├── org.opensearch.flint.spark.ppl.tpch.TPCHQueryITSuite.html
│  ├── org.opensearch.flint.spark.sessioncatalog.FlintSparkSessionCatalogMaterializedViewITSuite.html
│  └── org.opensearch.flint.spark.sessioncatalog.FlintSparkSessionCatalogSkippingIndexITSuite.html
├── ppl-spark-integration
│  ├── css
│  ├── images
│  ├── js
│  ├── index.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanAggregationQueriesTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanAppendColCommandTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanBasicQueriesTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanBetweenExpressionTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanCastTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanCorrelationQueriesTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanCryptographicFunctionsTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanDateTimeFunctionsTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanDedupeTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanEvalTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanEventstatsTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanExistsSubqueryTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanExpandCommandTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanFieldSummaryTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanFillnullCommandTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanFiltersTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanFlattenCommandTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanGeoipFunctionTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanGrokTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanInSubqueryTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanJoinTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanJsonFunctionsTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanLambdaFunctionsTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanMathFunctionsTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanNestedQueriesTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanParenthesizedConditionTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanParseCidrmatchTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanParseTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanPatternsTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanRenameTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanScalarSubqueryTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanStringFunctionsTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanTimeFunctionsTranslatorTestSuite.html
│  ├── org.opensearch.flint.spark.ppl.PPLLogicalPlanTopAndRareQueriesTranslatorTestSuite.html
│  └── org.opensearch.flint.spark.ppl.PPLLogicalPlanTrendlineCommandTranslatorTestSuite.html
└── sql-job
   ├── css
   ├── images
   ├── js
   ├── index.html
   ├── org.apache.spark.sql.FlintJobTest.html
   ├── org.apache.spark.sql.FlintREPLTest.html
   ├── org.apache.spark.sql.util.CleanerFactoryTest.html
   ├── org.apache.spark.sql.WarmpoolTest.html
   ├── org.opensearch.sql.FlintDelegatingSessionCatalogTest.html
   └── org.opensearch.sql.SQLJobTest.html
```

### PR DESCRIPTION
**Pull request by seankao-az**
### Description
Built upon the existing rate limiter:
* #1011 
* #1027

Adding the following enhancements:
* Multi-signal feedback
  * Measure request latency and decrease rate limit if high latency
  * Decrease rate limit to minimum if request timeout
* Rate limit unit change to byte/s from #doc/s
* Update to stabilized rate increase (#1027):
  * `RequestRateMeter` estimates current rate with a sliding window of size 10s (previously 3s). This is to account for burst permits allowed by guava rate limiter. A slightly larger window will result in less fluctuation in current rate estimation.
  * For example, if 10 permits were acquired in a burst, and response is received after 5 seconds, then:
    * With 3s window, when receiving the response, estimated current rate would be 0, because there wasn't any permits acquired in the past 3 seconds. This will block rate increase.
    * With 10s window, estimated current rate will be non-zero.
* Stabilized decrease rate: Decrease rate has a cooldown. Usually when a failure or high latency happens, multiple requests will have the same signal and this results in rate limit quickly shrinking multiple times exponentially. The cooldown mechanism is to stabilize the rate limit decreasing. Bad signals are ignored when decrease is still in cooldown.

Spark properties remain the same as #1011 (only updated default values)
Except that we now use bytes string (e.g. 100kb) instead of number (e.g. 100000) for readability.

Some notes on code changes:
* Move rate limiter related files to its own module
* Decouple rate setting from the client that uses the rate limit. Now the client only reports feedback, and rate limiter adjusts itself based on the feedback.
* Use `java.time.Clock` instead of `System.currentTimeMillis()` for tracking time for some classes, for stubbing clock in tests.

Infra:
* Fix #1097 so that unit tests for this rate limiter change can be run in GitHub CI as well. This is done by changing `sbt integtest/integration` into `sbt test integtest/integration` in the workflow. This makes the CI runtime into 41 min (from 38 min)
* Fix some other minor test failures exposed by above change
  * Fix `RetryableHttpAsyncClientSuite`
  * Ignore `OpenSearchClientUtilsSuite` — it passes when it's run by itself but always fail when run in `sbt test`. Updated in #1097 to track this

### Related Issues
* #1084 
* #1086

### Check List
- [x] Updated documentation
- [x] Implemented unit tests
- [x] New added source code should include a copyright header
- [x] Commits are signed per the DCO using `--signoff`
- [x] Add `backport 0.x` label if it is a stable change which won't break existing feature

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiter.java
[the remark this answers is not in the document]
Comment (seankao-az) [reply flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiter.java:1]: good point

[the remark this answers is not in the document]
Comment (seankao-az) [reply flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiter.java:1]: done

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiter.java [hunk 1]
```diff
@@ -3,18 +3,16 @@
...
 
   void acquirePermit(int permits);
 
-  void increaseRate();
-
-  void decreaseRate();
-
   long getRate();
 
+  void adaptToFeedback(RequestFeedback feedback);
```
Comment (dai-chen) [inline flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiter.java:15]: Could you add missing Javadoc?

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterImpl.java [hunk 2]
```diff
@@ -0,0 +1,182 @@
...
+  @Override
+  public long getRate() {
+    return (long) this.rateLimiter.getRate();
+  }
+
+  /**
+   * Adapt rate limit based on multi signal feedback.
+   */
+  @Override
+  public void adaptToFeedback(RequestFeedback feedback) {
```
Comment (dai-chen) [inline flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterImpl.java:105]: I'm thinking probably we can leverage `RequestFeedback` abstraction, each feedback class can have its metrics and adapt logic related?

File: docs/index.md [hunk 3]
```diff
@@ -536,10 +536,10 @@ In the index mapping, the `_meta` and `properties`field stores meta and schema i
...
-- `spark.datasource.flint.write.bulk.rate_limit_per_node.decrease_ratio`: [Experimental] Adaptive rate limit decrease ratio for bulk request per worker node, if rate limit enabled. Must be between 0 and 1. Default is 0.8.
+- `spark.datasource.flint.write.bulk.rate_limit_per_node.min`: [Experimental] Lower limit (documents/sec) for adaptive rate limiting for bulk request per worker node, if rate limit enabled. The adaptive rate will not drop below this value. Must be greater than 0. Default is 50000.
+- `spark.datasource.flint.write.bulk.rate_limit_per_node.max`: [Experimental] Upper limit (documents/sec) for adaptive rate limiting for bulk request per worker node, if rate limit enabled. The adaptive rate will not exceed this value. Set to -1 for no upper bound. Default is 350000.
+- `spark.datasource.flint.write.bulk.rate_limit_per_node.increase_step`: [Experimental] Adaptive rate limit increase step for bulk request per worker node, if rate limit enabled. Must be greater than 0. Default is 20000.
```
Comment (dai-chen) [inline docs/index.md:541]: "Rate limit unit change to byte/s from #doc/s" Do you mean the unit of all these are bytes now? The doc here still says documents/sec?

Comment (seankao-az) [reply docs/index.md:541]: nice catch. missed this

File: flint-core/src/test/scala/org/opensearch/flint/core/storage/OpenSearchClientUtilsSuite.scala [hunk 4]
```diff
@@ -5,9 +5,11 @@
 
 package org.opensearch.flint.core.storage
 
+import org.scalatest.Ignore
 import org.scalatest.flatspec.AnyFlatSpec
 import org.scalatest.matchers.should.Matchers
 
+@Ignore
```
[the remark this answers is not in the document]
Comment (seankao-az) [reply flint-core/src/test/scala/org/opensearch/flint/core/storage/OpenSearchClientUtilsSuite.scala:12]: seems scalatest Ignore couldn't add reason/message. Added as comment instead.

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiter.java (hunk 1 above)
Comment (seankao-az) [reply flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiter.java:15]: Javadoc are added in the implementation class `BulkRequestRateLimiter`. I decided doc in the interface isn't required, because it's used purely for the NoOp class when rate limiting is disabled. Effectively we always use the one and only `BulkRequestRateLimiterImpl`.

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterImpl.java (hunk 2 above)
Comment (seankao-az) [reply flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterImpl.java:111]: i can make the change

Comment (seankao-az) [reply flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterImpl.java:138]: I ended up with kind of a hybrid solution.. since the adapt logic depends on both the configs and some global states, I think it's simpler to keep them in the rate limiter itself, and have the `RequestFeedback` as a dispatcher.
It's possible to completely move the rate adjustment logic away from the rate limiter but that will result in a lot more boilerplate code.

File: flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java [hunk 5]
```diff
@@ -43,7 +43,7 @@ public final class MetricConstants {
     /**
      * Metric name for opensearch bulk request rate limit
      */
-    public static final String OS_BULK_RATE_LIMIT_METRIC = "opensearch.bulk.rateLimit.documentsPerSecond.count";
+    public static final String OS_BULK_RATE_LIMIT_METRIC = "opensearch.bulk.rateLimit.bytesPerSecond.count";
```
[the remark this answers is not in the document]
Comment (seankao-az) [reply flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java:46]: Its current actual value. Adding the `.count` is merely to have it appear in CloudWatch without modifying `metrics.properties` we use in production. We only allow for specific suffices.

File: .github/workflows/test-and-build-workflow.yml [hunk 6]
```diff
@@ -33,11 +33,11 @@ jobs:
...
+        run: sbt test integtest/integration
 
       - name: Upload test report
         if: always() # Ensures the artifact is saved even if tests fail
         uses: actions/upload-artifact@v4
         with:
           name: test-reports
-          path: target/test-reports # Adjust this path if necessary
\ No newline at end of file
+          path: target/test-reports # Adjust this path if necessary
```
[the remark this answers is not in the document]
Comment (seankao-az) [reply .github/workflows/test-and-build-workflow.yml:43]: I think in general we do want a new line at end of file. This was the only one without a new line

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/TimeoutRequestFeedback.java [hunk 7]
```diff
@@ -0,0 +1,27 @@
+/*
+ * Copyright OpenSearch Contributors
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+package org.opensearch.flint.core.storage.ratelimit;
+
+/**
+ * Represents a timeout event in bulk request processing.
+ * Uses singleton pattern since timeout feedback doesn't need additional state.
```
[the remark this answers is not in the document]
Comment (seankao-az) [reply flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/TimeoutRequestFeedback.java:10]: No.. well this isn't really necessary.
It was only meant to re-use the TimeoutRequestFeedback instance without re-creating it. I can make it so that it creates new instance, similar to the other two concrete RequestFeedback

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiter.java (hunk 1 above)
Comment (seankao-az) [reply flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiter.java:19]: javadoc added

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/TimeoutRequestFeedback.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (seankao-az) [reply flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/TimeoutRequestFeedback.java]: removed

File: flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (noCharger) [reply flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java:46]: the correct way is to modify metrics.properties but it's okay for now

[the remark this answers is not in the document]
Comment (seankao-az) [reply flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java:46]: I think we want to have a more generic suffix defined in metrics.properties. Right now it only allows for count, processingTime, latency. Which is pretty restrictive and not flexible

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterImpl.java [hunk 8]
```diff
@@ -0,0 +1,201 @@
...
+    this.rateLimiter.acquire(permits);
+    LOG.info("Acquired " + permits + " permits");
+    requestRateMeter.addDataPoint(clock.millis(), permits);
+  }
+
+  @Override
+  public void adaptToFeedback(RequestFeedback feedback) {
+    long newRateLimit = feedback.suggestNewRateLimit(this);
+    setRate(newRateLimit);
+  }
```
Comment (dai-chen) [inline flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterImpl.java:115]: So the current call stack is like `BulkRequestRateLimiter.adaptToFeedback()` -> `RequestFeedback.suggestNewRateLimit()` -> `BulkRequestRateLimiter(FeedbackHandler).handleFeedback()`. I'm thinking any chance to simplify this and remove one call?

**Review by dai-chen — APPROVED** [review]
Thanks for the changes!

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchClientUtils.java [hunk 9]
```diff
@@ -27,6 +27,7 @@
 import org.opensearch.flint.core.RestHighLevelClientWrapper;
 import org.opensearch.flint.core.auth.ResourceBasedAWSRequestSigningApacheInterceptor;
 import org.opensearch.flint.core.http.RetryableHttpAsyncClient;
+import org.opensearch.flint.core.storage.ratelimit.BulkRequestRateLimiterHolder;
```
Comment (noCharger) [inline flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchClientUtils.java:30]: nit: unused import?

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchBulkWrapper.java [hunk 10]
```diff
@@ -9,6 +9,8 @@
 import dev.failsafe.FailsafeException;
 import dev.failsafe.RetryPolicy;
 import dev.failsafe.function.CheckedPredicate;
+
+import java.time.Clock;
```
Comment (noCharger) [inline flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchBulkWrapper.java:13]: why use this instead of System.currentTimeMillis();

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterImpl.java (hunk 8 above)
Comment (seankao-az) [reply flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterImpl.java:115]: Can instead pass all the all context (config, current state, etc.) to suggestNewRateLimit and has it directly calculate without dispatching

**Review by noCharger — APPROVED** [review]
Thanks for the change!

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchBulkWrapper.java (hunk 10 above)
Comment (seankao-az) [reply flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchBulkWrapper.java:13]: for stubbing in test cases to better control test behavior

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchClientUtils.java (hunk 9 above)
Comment (seankao-az) [reply flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchClientUtils.java:30]: it's used. I think this line is needed because of the new sub-module `ratelimit`

**Comment by seankao-az** [comment]
As discussed offline, updating config to use bytes string (e.g. 100kb) instead of number (e.g. 100000) for readability.

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchBulkWrapper.java (hunk 10 above)
Comment (seankao-az) [reply flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchBulkWrapper.java:13]: double checked the code.. I think at one point there was a need for using a Clock here. Now there might have no need in this `OpenSearchBulkWrapper` class

**Comment by seankao-az** [comment]
As discussed offline, changing the configs to use string (e.g. 100kb) instead of number (e.g. 100000) for readability.
@dai-chen I also updated the default values to the production config for 2 executors

File: flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterImpl.java (hunk 8 above)
Comment (dai-chen) [reply flint-core/src/main/scala/org/opensearch/flint/core/storage/ratelimit/BulkRequestRateLimiterImpl.java:115]: Sure, we can refactor later.
