### PR TITLE
Join side aliases should be optional

### LINKED ISSUE #857: [BUG] Side aliases in JOIN command should be optional
**What is the bug?**
Currently, the syntax of JOIN command requires side aliases to be present as following

**leftAlias**
- Syntax: `left = <leftAlias>`
- Required
- Description: The subquery alias to use with the left join side, to avoid ambiguous naming.

**rightAlias**
- Syntax: `right = <rightAlias>`
- Required
- Description: The subquery alias to use with the right join side, to avoid ambiguous naming.

But these required side aliases could cause a bug which hide the attribute references in table.
Imaging a case as following: Assume table1, table2, and table3 all contain a column `id`.
```sql
select
  *
from
  table1 t1,
  table2 t2,
  table3 t3
where
 t1.id = t2.id
 and t1.id = t3.id
```
The logical plan looks
```
'Project [*]
+- 'Filter (('t1.id = 't2.id) AND ('t1.id = 't3.id))
   +- 'Join Inner
      :- 'Join Inner
      :  :- 'SubqueryAlias t1
      :  :  +- 'UnresolvedRelation [table1], [], false
      :  +- 'SubqueryAlias t2
      :     +- 'UnresolvedRelation [table2], [], false
      +- 'SubqueryAlias t3
         +- 'UnresolvedRelation [table3], [], false
```
To rewrite above SQL query to PPL query, we will get
```sql
source = table1
| join left = t1 right = t2 ON t1.id = t2.id table2
| join left = l1 right = t3 ON t1.id = t3.id table3 // <------ issue here! 
```
The PPL query throws an exception with message:
> `t1`.`id` cannot be resolved, Did you mean one of the following? [`l1`.`id`, `l1`.`id`, `t3`.`id`].

It because the new left alias `l1` overrides the table alias `t1` and `t2`.
Its logical plan looks
```
'Project [*]
+- 'Filter (('t1.id = 't2.id) AND ('t1.id = 't3.id)). <------ t1.id cannot be resolved
   +- 'Join Inner
      :- 'SubqueryAlias l1  <------ issue root cause
      :  +- 'Join Inner
      :    :- 'SubqueryAlias t1
      :    :  +- 'UnresolvedRelation [table1], [], false
      :    +- 'SubqueryAlias t2
      :       +- 'UnresolvedRelation [table2], [], false
      +- 'SubqueryAlias t3
         +- 'UnresolvedRelation [table3], [], false
```

### PR DESCRIPTION
**Pull request by LantaoJin**
### Description
Imaging a case as following: Assume table1, table2, and table3 all contain a column `id`.
```sql
select
  *
from
  table1 t1,
  table2 t2,
  table3 t3
where
 t1.id = t2.id
 and t1.id = t3.id
```
To rewrite above SQL query to PPL query, we will get
```sql
source = table1
| join left = t1 right = t2 ON t1.id = t2.id table2
| join left = l1 right = t3 ON t1.id = t3.id table3 // <------ issue here! 
```

The PPL query throws an exception with message:
> `t1`.`id` cannot be resolved, Did you mean one of the following? [`l1`.`id`, `l1`.`id`, `t3`.`id`].

It because the **required left side alias** `l1` overrides the table alias `t1` and `t2`.

Its logical plan looks
```
'Project [*]
+- 'Filter (('t1.id = 't2.id) AND ('t1.id = 't3.id)) <------ t1.id cannot be resolved
   +- 'Join Inner
      :- 'SubqueryAlias l1  <------ issue root cause
      :  +- 'Join Inner
      :    :- 'SubqueryAlias t1
      :    :  +- 'UnresolvedRelation [table1], [], false
      :    +- 'SubqueryAlias t2
      :       +- 'UnresolvedRelation [table2], [], false
      +- 'SubqueryAlias t3
         +- 'UnresolvedRelation [table3], [], false
```

Check #857 for details

### Related Issues
Resolves #857 

### Check List
- [x] Updated documentation (docs/ppl-lang/README.md)
- [x] Implemented unit tests
- [x] Implemented tests for combination with other commands
- [ ] New added source code should include a copyright header
- [x] Commits are signed per the DCO using `--signoff`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java [hunk 1]
```diff
@@ -10,47 +10,24 @@
...
-    this(tableName, null);
-  }
-
-  public Relation(UnresolvedExpression tableName, String alias) {
-    this.tableName = Arrays.asList(tableName);
-    this.alias = alias;
-  }
-
-  /** Optional alias name for the relation. */
-  @Setter @Getter private String alias;
```
Comment (LantaoJin) [inline ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java:43]: The `alias` in Relation could be removed since we have the `SubqueryAlias` in AST: https://github.com/opensearch-project/opensearch-spark/blob/main/ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/SubqueryAlias.java

Remaining this member causes potential issue if conflicts

File: ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java [hunk 2]
```diff
@@ -10,47 +10,24 @@
...
-
-  /**
-   * Return table name.
-   *
-   * @return table name
-   */
-  public List<String> getTableName() {
```
Comment (LantaoJin) [inline ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java:50]: Never used.

File: ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanJoinTranslatorTestSuite.scala [hunk 3]
```diff
@@ -271,9 +271,9 @@ class PPLLogicalPlanJoinTranslatorTestSuite
       pplParser,
       s"""
          | source = $testTable1
-         | | inner JOIN left = l,right = r ON l.id = r.id $testTable2
-         | | left JOIN left = l,right = r ON l.name = r.name $testTable3
-         | | cross JOIN left = l,right = r $testTable4
+         | | inner JOIN left = l right = r ON l.id = r.id $testTable2
+         | | left JOIN left = l right = r ON l.name = r.name $testTable3
+         | | cross JOIN left = l right = r $testTable4
```
Comment (LantaoJin) [inline ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanJoinTranslatorTestSuite.scala:276]: Comma is optional, I am trying to reduce this usage. But keep the comma won't fail query.

File: ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java [hunk 4]
```diff
@@ -485,9 +497,8 @@ public UnresolvedPlan visitTableOrSubqueryClause(OpenSearchPPLParser.TableOrSubq
 
   @Override
   public UnresolvedPlan visitTableSourceClause(OpenSearchPPLParser.TableSourceClauseContext ctx) {
-    return ctx.alias == null
-        ? new Relation(ctx.tableSource().stream().map(this::internalVisitExpression).collect(Collectors.toList()))
-        : new Relation(ctx.tableSource().stream().map(this::internalVisitExpression).collect(Collectors.toList()), ctx.alias.getText());
+    Relation relation = new Relation(ctx.tableSource().stream().map(this::internalVisitExpression).collect(Collectors.toList()));
+    return ctx.alias != null ? new SubqueryAlias(ctx.alias.getText(), relation) : relation;
```
Comment (LantaoJin) [inline ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java:501]: We add `SubqueryAlias` ast node instead of adding the alias string into `Relation`.

File: ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java (hunk 2 above)
Comment (LantaoJin) [inline ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java:50]: Never used.

**Comment by LantaoJin** [comment]
Without this fixing, q21 in TPCH couldn't be rewritten to PPL. Link https://github.com/opensearch-project/opensearch-spark/issues/806

File: ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java [hunk 5]
```diff
@@ -10,47 +10,24 @@
...
 /** Logical plan node of Relation, the interface for building the searching sources. */
-@AllArgsConstructor
 @ToString
+@Getter
 @EqualsAndHashCode(callSuper = false)
 @RequiredArgsConstructor
 public class Relation extends UnresolvedPlan {
   private static final String COMMA = ",";
 
   private final List<UnresolvedExpression> tableName;
```
Comment (YANG-DB) [inline ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java:29]: @LantaoJin lates change the name to indicate it may contain multi-part

File: ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java (hunk 1 above)
Comment (YANG-DB) [reply ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java:43]: @LantaoJin can u give an example for a union query ?
source = a as table_a, b as table_b, c as table_c |  ...

File: ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java [hunk 6]
```diff
@@ -288,4 +265,21 @@ public static Optional<UnresolvedRelation> findRelation(LogicalPlan plan) {
...
+     * Resolve the join condition with the given function.
+     * A flag will be set to true ahead expression resolving, then false after resolving.
+     * @param expr
+     * @param transformFunction
+     * @return
+     */
+    public Expression resolveJoinCondition(
+            UnresolvedExpression expr,
+            BiFunction<UnresolvedExpression, CatalystPlanContext, Expression> transformFunction) {
+        isResolvingJoinCondition = true;
```
Comment (YANG-DB) [inline ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java:280]: can u make this an atomic bool ?

File: ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java [hunk 7]
```diff
@@ -155,14 +155,26 @@ public UnresolvedPlan visitJoinCommand(OpenSearchPPLParser.JoinCommandContext ct
...
-      throw new SyntaxCheckException("'AS' is not allowed in right subquery, use right=<rightAlias> instead");
+      rightAlias = Optional.of(ctx.tableOrSubqueryClause().alias.getText());
     }
+    if (ctx.sideAlias().rightAlias != null) {
+      rightAlias = Optional.of(ctx.sideAlias().rightAlias.getText());
+    }
+
     UnresolvedPlan rightRelation = visit(ctx.tableOrSubqueryClause());
-    UnresolvedPlan right = new SubqueryAlias(rightAlias, rightRelation);
+    UnresolvedPlan right;
```
Comment (YANG-DB) [inline ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java:168]: please add some comment explaining the condition

**Review by YANG-DB — CHANGES_REQUESTED** [review]

File: ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java (hunk 1 above)
Comment (LantaoJin) [reply ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java:43]: > @LantaoJin can u give an example for a union query ? source = a as table_a, b as table_b, c as table_c | ...

No, we didn't support this pattern, see https://github.com/opensearch-project/opensearch-spark/blob/b183b4a297cb6cdb1cdc55b2b7047cad56b63a05/ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4#L323

But we supported the pattern:
`source = table1, table2, table3 as t | where t.name = 'Molly'`
The plan of above is
```
'Union true, true
:- 'Project [*]
:  +- 'Filter ('t.name = Molly)
:     +- 'SubqueryAlias t
:        +- 'UnresolvedRelation [table1], [], false
:- 'Project [*]
:  +- 'Filter ('t.name = Molly)
:     +- 'SubqueryAlias t
:        +- 'UnresolvedRelation [table2], [], false
+- 'Project [*]
   +- 'Filter ('t.name = Molly)
      +- 'SubqueryAlias t
         +- 'UnresolvedRelation [table3], [], false
```

File: ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java (hunk 5 above)
Comment (LantaoJin) [reply ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java:29]: done

File: ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java (hunk 6 above)
Comment (LantaoJin) [reply ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java:280]: `CatalystPlanContext` is generated by each query. All members in `CatalystPlanContext` should thread-safe.

File: ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java (hunk 7 above)
Comment (LantaoJin) [reply ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java:168]: done

File: ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java (hunk 6 above)
Comment (YANG-DB) [reply ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java:280]: lets add this note on the `CatalystPlanContext` class description for better clarity

**Review by YANG-DB — APPROVED** [review]

**Comment by YANG-DB** [comment]
@LantaoJin also plz resolve conflicts...

**Comment by LantaoJin** [comment]
Conflicts is related to imports. CI tests succeed with the related files. Merging to main.
