### PR TITLE
Multiple tables as join right without subsearch is not allowed

### LINKED ISSUE #1073: [BUG] Join queries with multiple tables as join right fails with stack overflow error
**What is the bug?**
```
search source=table_a
  | INNER JOIN on column1 = column5 table_b, table_b_2
  | fields column1, column2, column3, column5
```
Failed with stack overflow error.

We can disable it to support two-table join only. But should we support query such as following query?
```
search source=table_a
  | INNER JOIN on column1 = column5 [search source = table_b, table_b_2 ]
  | fields column1, column2, column3, column5
```
This query will stackoverflow in Spark internal as well.

### PR DESCRIPTION
**Pull request by LantaoJin**
### Description
Multiple tables as join right without subsearch is not allowed:
- `JOIN on id = uid table1,table2` is not allowed
- `JOIN on id = uid table1,table2 as t2` is not allowed
- `JOIN on id = uid [ source = table1,table2 ]` is allowed
- `JOIN on id = uid [ source = table1,table2 ] as t2` is allowed

### Related Issues
Resolves #1073 

### Check List
- [ ] Updated documentation (docs/ppl-lang/README.md)
- [x] Implemented unit tests
- [ ] Implemented tests for combination with other commands
- [ ] New added source code should include a copyright header
- [x] Commits are signed per the DCO using `--signoff`
- [x] Add `backport 0.x` label if it is a stable change which won't break existing feature

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java [hunk 1]
```diff
@@ -354,8 +354,9 @@ public LogicalPlan visitJoin(Join node, CatalystPlanContext context) {
             Optional<Expression> joinCondition = node.getJoinCondition()
                 .map(c -> expressionAnalyzer.analyzeJoinCondition(c, context));
             context.resetNamedParseExpressions();
+            LogicalPlan join = join(left, right, node.getJoinType(), joinCondition, node.getJoinHint()).clone();
             context.retainAllPlans(p -> p);
-            return join(left, right, node.getJoinType(), joinCondition, node.getJoinHint());
+            return join;
```
Comment (LantaoJin) [inline ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java:359]: The stackoverflow is due to plans were retained before building a join. This bug happened when the Union was added in ppl `source = table, table2`. So we should clone it then call `retainAllPlans`.

**Comment by LantaoJin** [comment]
Does anyone know how to check which query failed in end2end test?

**Comment by LantaoJin** [comment]
ping @penghuo @ykmr1224 @YANG-DB

**Review by YANG-DB — APPROVED** [review]
